on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Single Page application
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci && npm run build

        # publish to cloudflare pages
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hkepc-ir-app
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
